#!/usr/bin/env bash
# mount_mcp_as_cli.sh
#
# Mounts MCP servers as local CLI tools, allowing agents to call MCP tools
# directly from the command line using a familiar shell interface.
#
# Reads the manifest saved by start_mcp_gateway.sh, queries each server for
# its tool list, and generates a standalone CLI wrapper script for each server.
#
# Generated CLI wrapper usage:
#   <server> --help                        Show all available commands
#   <server> <command> --help              Show help for a specific command
#   <server> <command> [--param value...]  Execute a command
#
# Environment variables:
#   MCP_GATEWAY_API_KEY  API key for MCP gateway authentication (required)
#
# Outputs (GitHub Actions):
#   mounted-servers  Comma-separated list of mounted server names
#
# Side effects:
#   - Creates /tmp/gh-aw/mcp-cli/bin/ with CLI wrapper scripts (chmod 555)
#   - Creates /tmp/gh-aw/mcp-cli/tools/ with per-server tool JSON caches
#   - Appends /tmp/gh-aw/mcp-cli/bin to $GITHUB_PATH

set -eo pipefail

MANIFEST="/tmp/gh-aw/mcp-cli/manifest.json"
CLI_BIN_DIR="/tmp/gh-aw/mcp-cli/bin"
TOOLS_DIR="/tmp/gh-aw/mcp-cli/tools"

# Internal MCP infrastructure servers that should not be exposed as user-facing CLIs
INTERNAL_SERVERS=("safeoutputs" "mcp-scripts")

is_internal_server() {
  local name="$1"
  for internal in "${INTERNAL_SERVERS[@]}"; do
    if [ "$name" = "$internal" ]; then
      return 0
    fi
  done
  return 1
}

if [ ! -f "$MANIFEST" ]; then
  echo "No MCP CLI manifest found at $MANIFEST, skipping CLI mounting"
  exit 0
fi

echo "Mounting MCP servers as CLI tools..."
mkdir -p "$CLI_BIN_DIR" "$TOOLS_DIR"

MOUNTED_SERVERS=()

while IFS= read -r server_entry; do
  SERVER_NAME=$(echo "$server_entry" | jq -r '.name')
  SERVER_URL=$(echo "$server_entry" | jq -r '.url')

  # Skip internal infrastructure servers
  if is_internal_server "$SERVER_NAME"; then
    echo "Skipping internal server: $SERVER_NAME"
    continue
  fi

  echo "Mounting MCP server '$SERVER_NAME' (url: $SERVER_URL)..."

  TOOLS_FILE="$TOOLS_DIR/$SERVER_NAME.json"

  # Query tools list from the MCP server via the gateway
  # Step 1: Initialize to establish a session (required by stateful transports)
  INIT_RESP=$(curl -s -i --max-time 15 -X POST "$SERVER_URL" \
    -H "Authorization: Bearer $MCP_GATEWAY_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{},"clientInfo":{"name":"mcp-cli-mount","version":"1.0.0"},"protocolVersion":"2024-11-05"}}' \
    2>/dev/null || echo "")

  SESSION_ID=$(echo "$INIT_RESP" | grep -i "^mcp-session-id:" | awk '{print $2}' | tr -d '\r' 2>/dev/null || echo "")

  # Step 2: Fetch the tool list
  SESSION_HEADER_ARG=()
  if [ -n "$SESSION_ID" ]; then
    SESSION_HEADER_ARG=(-H "Mcp-Session-Id: $SESSION_ID")
  fi

  TOOLS_RESP=$(curl -s --max-time 15 -X POST "$SERVER_URL" \
    -H "Authorization: Bearer $MCP_GATEWAY_API_KEY" \
    -H "Content-Type: application/json" \
    "${SESSION_HEADER_ARG[@]}" \
    -d '{"jsonrpc":"2.0","id":2,"method":"tools/list"}' \
    2>/dev/null || echo "{}")

  # Save tools to cache file (empty array if unavailable)
  if ! echo "$TOOLS_RESP" | jq -c '.result.tools // []' > "$TOOLS_FILE" 2>/dev/null; then
    echo "[]" > "$TOOLS_FILE"
  fi
  chmod 644 "$TOOLS_FILE"

  TOOL_COUNT=$(jq '. | length' "$TOOLS_FILE" 2>/dev/null || echo "0")
  echo "  Found $TOOL_COUNT tool(s)"

  # Generate CLI wrapper script for this server
  CLI_SCRIPT="$CLI_BIN_DIR/$SERVER_NAME"

  # Write header with values baked in at creation time
  cat > "$CLI_SCRIPT" << SCRIPT_EOF
#!/usr/bin/env bash
# MCP CLI wrapper for: $SERVER_NAME
# Auto-generated by gh-aw. Do not modify.
#
# Usage:
#   $SERVER_NAME --help                        Show all available commands
#   $SERVER_NAME <command> --help              Show help for a specific command
#   $SERVER_NAME <command> [--param value...]  Execute a command
#
# Connects to: $SERVER_URL

SERVER_NAME="$SERVER_NAME"
SERVER_URL="$SERVER_URL"
TOOLS_FILE="$TOOLS_FILE"

# API key injected from the workflow environment
API_KEY="\${MCP_GATEWAY_API_KEY:-}"
if [ -z "\$API_KEY" ]; then
  echo "Error: MCP_GATEWAY_API_KEY environment variable is not set" >&2
  exit 1
fi

load_tools() {
  if [ -f "\$TOOLS_FILE" ]; then
    cat "\$TOOLS_FILE"
  else
    echo "[]"
  fi
}

show_help() {
  local tools
  tools=\$(load_tools)
  echo "Usage: \$SERVER_NAME <command> [options]"
  echo ""
  echo "Available commands:"
  if command -v jq &>/dev/null && echo "\$tools" | jq -e 'length > 0' >/dev/null 2>&1; then
    echo "\$tools" | jq -r '.[] | "  \(.name)\t\(.description // "No description")"' \
      | column -t -s \$'\t' 2>/dev/null \
      || echo "\$tools" | jq -r '.[] | "  \(.name)  \(.description // "")"'
  else
    echo "  (tool list unavailable)"
  fi
  echo ""
  echo "Run '\$SERVER_NAME <command> --help' for more information on a command."
}

show_tool_help() {
  local tool_name="\$1"
  local tools tool
  tools=\$(load_tools)
  tool=\$(echo "\$tools" | jq -r ".[] | select(.name == \"\$tool_name\")" 2>/dev/null || echo "")

  if [ -z "\$tool" ]; then
    echo "Error: Unknown command '\$tool_name'" >&2
    echo "Run '\$SERVER_NAME --help' to see available commands." >&2
    exit 1
  fi

  echo "Command: \$tool_name"
  echo "Description: \$(echo "\$tool" | jq -r '.description // "No description"')"

  local has_props
  has_props=\$(echo "\$tool" | jq -r 'has("inputSchema") and ((.inputSchema.properties // {}) | length > 0)')

  if [ "\$has_props" = "true" ]; then
    echo ""
    echo "Options:"
    echo "\$tool" | jq -r '.inputSchema.properties | to_entries[] |
      "  --\(.key)  \(.value.description // .value.type // "string")"'
    local required
    required=\$(echo "\$tool" | jq -r '(.inputSchema.required // []) | join(", ")')
    if [ -n "\$required" ]; then
      echo ""
      echo "Required: \$required"
    fi
  fi
}

call_tool() {
  local tool_name="\$1"
  shift

  # Parse --key value arguments into a JSON object
  local args="{}"
  while [[ \$# -gt 0 ]]; do
    if [[ "\$1" == --* ]]; then
      local key="\${1#--}"
      if [[ \$# -ge 2 && "\$2" != --* ]]; then
        local val="\$2"
        args=\$(echo "\$args" | jq --arg k "\$key" --arg v "\$val" '. + {(\$k): \$v}')
        shift 2
      else
        args=\$(echo "\$args" | jq --arg k "\$key" '. + {(\$k): true}')
        shift 1
      fi
    else
      shift
    fi
  done

  # Initialize MCP session to establish a stateful connection
  local init_resp session_id
  init_resp=\$(curl -s -i --max-time 30 -X POST "\$SERVER_URL" \
    -H "Authorization: Bearer \$API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{},"clientInfo":{"name":"mcp-cli","version":"1.0.0"},"protocolVersion":"2024-11-05"}}' \
    2>/dev/null || echo "")

  session_id=\$(echo "\$init_resp" | grep -i "^mcp-session-id:" | awk '{print \$2}' | tr -d '\r' 2>/dev/null || echo "")

  # Build tool call request
  local request
  request=\$(jq -n --arg name "\$tool_name" --argjson args "\$args" \
    '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":\$name,"arguments":\$args}}')

  # Invoke the tool via the gateway
  local session_header_args=()
  if [ -n "\$session_id" ]; then
    session_header_args=(-H "Mcp-Session-Id: \$session_id")
  fi

  local response
  response=\$(curl -s --max-time 120 -X POST "\$SERVER_URL" \
    -H "Authorization: Bearer \$API_KEY" \
    -H "Content-Type: application/json" \
    "\${session_header_args[@]}" \
    -d "\$request" \
    2>/dev/null)

  # Surface JSON-RPC errors
  if echo "\$response" | jq -e '.error' >/dev/null 2>&1; then
    local err_msg err_code
    err_msg=\$(echo "\$response" | jq -r '.error.message // "Unknown error"')
    err_code=\$(echo "\$response" | jq -r '.error.code // ""')
    if [ -n "\$err_code" ]; then
      echo "Error [\$err_code]: \$err_msg" >&2
    else
      echo "Error: \$err_msg" >&2
    fi
    exit 1
  fi

  # Print result content
  if echo "\$response" | jq -e '.result.content' >/dev/null 2>&1; then
    echo "\$response" | jq -r '.result.content[] |
      if .type == "text" then .text
      elif .type == "image" then "[image data - \(.mimeType // "unknown")]"
      else (. | tostring)
      end'
  elif echo "\$response" | jq -e '.result' >/dev/null 2>&1; then
    echo "\$response" | jq -r '.result'
  else
    echo "\$response"
  fi
}

# Main entry point
if [[ \$# -eq 0 || "\$1" == "--help" || "\$1" == "-h" ]]; then
  show_help
  exit 0
fi

COMMAND="\$1"
shift

if [[ "\$1" == "--help" || "\$1" == "-h" ]]; then
  show_tool_help "\$COMMAND"
  exit 0
fi

call_tool "\$COMMAND" "\$@"
SCRIPT_EOF

  chmod 755 "$CLI_SCRIPT"
  MOUNTED_SERVERS+=("$SERVER_NAME")
  echo "  ✓ Mounted as: $CLI_SCRIPT"
done < <(jq -c '.servers[]' "$MANIFEST")

if [ "${#MOUNTED_SERVERS[@]}" -eq 0 ]; then
  echo "No MCP servers mounted as CLI tools"
  exit 0
fi

# Lock the CLI bin directory to prevent modification by the agent
chmod 555 "$CLI_BIN_DIR"

# Add CLI bin directory to PATH for subsequent steps
echo "$CLI_BIN_DIR" >> "$GITHUB_PATH"

echo ""
echo "Successfully mounted ${#MOUNTED_SERVERS[@]} MCP server(s) as CLI tools:"
for name in "${MOUNTED_SERVERS[@]}"; do
  echo "  - $name"
done
echo ""
echo "CLI bin directory: $CLI_BIN_DIR (read-only)"
echo "Added to PATH: yes (takes effect in subsequent steps)"

# Emit GitHub Actions step output with the list of mounted servers
printf "mounted-servers=%s\n" "$(
  IFS=','
  echo "${MOUNTED_SERVERS[*]}"
)" >> "$GITHUB_OUTPUT"
